baseURL: "https://restodeny.github.io"
AdSense: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7304615088166232"
     crossorigin="anonymous"></script>
title: Resto Deny
